// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"order-manager/internal/biz"
	"order-manager/internal/data"
	"order-manager/internal/service"
)

// Injectors from wire.go:

func initApp() *service.OrderService {
	orderRepo := data.NewOrderRepo()
	orderUseCase := biz.NewOrderUseCase(orderRepo)
	orderService := service.NewOrderService(orderUseCase)
	return orderService
}
